In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn as skl
import scipy as scp

In [2]:
titanic = pd.read_csv("./Titanic-Dataset.csv") 
titanic = titanic.loc[:, ["Age", "Fare", "SibSp", "Parch", "Survived"]]
titanic["family"] = titanic["SibSp"] + titanic["Parch"]
titanic.drop(columns= ["SibSp", "Parch"], inplace= True)
titanic.dropna(inplace= True)
titanic.sample(10)

      Age     Fare  Survived  family
40   40.0   9.4750         0       1
24    8.0  21.0750         0       4
875  15.0   7.2250         1       0
146  27.0   7.7958         1       0
419  10.0  24.1500         0       2
257  30.0  86.5000         1       0
14   14.0   7.8542         0       0
877  19.0   7.8958         0       0
678  43.0  46.9000         0       7
852   9.0  15.2458         0       2

In [3]:
x = titanic.drop(columns=["Survived"])
y = titanic["Survived"]

In [6]:
x_train, x_test, y_train, y_test = skl.model_selection.train_test_split(x, y, test_size= 0.2, random_state= 42)

In [7]:
dtc = skl.tree.DecisionTreeClassifier()

dtc.fit(x_train, y_train)

y_pred = dtc.predict(x_test)

skl.metrics.accuracy_score(y_test, y_pred)

0.6223776223776224

In [8]:
np.mean(skl.model_selection.cross_val_score(skl.tree.DecisionTreeClassifier(), x, y, scoring= "accuracy", cv= 10))

np.float64(0.6499608763693271)

In [9]:
trf = skl.compose.ColumnTransformer(transformers= [
    ('bin',skl.preprocessing.Binarizer(copy= False) , ["family"])
    ], remainder= "passthrough")

x_train_trf = trf.fit_transform(x_train)
x_test_trf = trf.transform(x_test)

x_train_trf = pd.DataFrame(data= x_train_trf, columns= x_train.columns)
x_train_trf

     Age  Fare    family
0    1.0  31.0   20.5250
1    1.0  26.0   14.4542
2    1.0  30.0   16.1000
3    0.0  33.0    7.7750
4    0.0  25.0   13.0000
..   ...   ...       ...
566  1.0  46.0   61.1750
567  0.0  25.0   13.0000
568  0.0  41.0  134.5000
569  1.0  33.0   20.5250
570  0.0  33.0    7.8958

[571 rows x 3 columns]

In [10]:
dtc_trf = skl.tree.DecisionTreeClassifier()

dtc_trf.fit(x_train_trf, y_train)

y_pred_trf = dtc_trf.predict(x_test_trf)

skl.metrics.accuracy_score(y_test, y_pred)

c:\Users\aliab\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

0.6223776223776224

In [11]:
np.mean(skl.model_selection.cross_val_score(skl.tree.DecisionTreeClassifier(), x, y, scoring= "accuracy", cv= 10))

np.float64(0.6583528951486699)