In [140]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn as skl
import scipy as scp

In [141]:
order = pd.read_csv("./orders.csv")
msg = pd.read_csv("./messages.csv")

In [142]:
order.sample(10)

           date  product_id  city_id  orders
468  2019-02-14        7140       18      20
855  2018-08-06        4809       14       1
751  2018-12-10        1603       16       1
780  2018-11-07         702        6       2
438  2018-12-31        1985       14      45
853  2019-08-11        7430        1       1
415  2018-09-07        1191       13      47
631  2019-06-30        4323        4       7
752  2019-06-21        6174        3      12
738  2019-05-27        7585       27       2

In [143]:
order.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   str
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), str(1)
memory usage: 31.4 KB

In [144]:
order.describe()

        product_id      city_id       orders
count  1000.000000  1000.000000  1000.000000
mean   3826.379000    16.371000    17.497000
std    2217.585914     8.554211    57.357841
min       5.000000     0.000000     1.000000
25%    1935.000000    13.000000     1.000000
50%    3810.000000    16.000000     4.000000
75%    5778.000000    25.000000    12.000000
max    7585.000000    30.000000  1004.000000

In [145]:
msg.sample(10)

                    date                                                msg
269  2014-07-06 00:03:00  п 30 поз с дев до 45 для встречи сейчас 096524...
904  2012-05-11 01:57:00                                     Андрей+Людмиоа
63   2013-05-12 00:22:00  Д. 22 ищу состоятельного и интересного П. 0976...
132  2013-10-27 23:34:00  симп. Парень ищет  Мужчину или СЕМ/ПАРУ. 06340...
710  2015-06-13 01:07:00  познакомлюсь сдевушкой незамужней от 35 лет 09...
195  2015-02-11 01:24:00  М38 ПОЗНАКОМИТСЯ С ДЕВУШКОЙ ОТ 29ЛЕТ ДЕТИ НЕ П...
660  2012-01-03 01:01:00  П27 Втарую палавинку с/о.с/с отвечу ммс0951232936
717  2015-02-06 22:49:00  .П 27 лет из МЛС нахожусь в Луг.обл ищу Д для ...
382  2012-01-31 00:58:00  7Хочу.познакомиться.с девчомкай.от 25-30 Я пар...
991  2016-08-30 01:20:00  познакрмлюсь с уравновешенным м.до 42л.для с/с...

In [146]:
msg.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   str
 1   msg     1000 non-null   str
dtypes: str(2)
memory usage: 15.8 KB

In [147]:
msg.describe()

                       date                                          msg
count                  1000                                         1000
unique                  999                                          966
top     2013-11-01 23:36:00  ласковая кошечка ищет своего ночного котика
freq                      2                                            4

In [148]:
order["date"] = pd.to_datetime(order["date"])
order.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[us]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[us](1), int64(3)
memory usage: 31.4 KB

In [149]:
msg["date"] = pd.to_datetime(msg["date"])
msg.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[us]
 1   msg     1000 non-null   str
dtypes: datetime64[us](1), str(1)
memory usage: 15.8 KB

# HANDLING DATE

In [150]:
# Extract Year, month, month name, day, day name, day of week, day of, week of year, quater
order["year"], order["month"], order["month_name"], order["week_of_year"], order["day"], order["day_name"], order["day_of_week"], order["day_of_year"], order["quater"] = order["date"].dt.year, order["date"].dt.month, order["date"].dt.month_name(), order["date"].dt.isocalendar().week, order["date"].dt.day, order["date"].dt.day_name(), order["date"].dt.dayofweek, order["date"].dt.dayofyear, order["date"].dt.quarter
order.sample(5)

,date,product_id,city_id,orders,year,month,month_name,week_of_year,day,day_name,day_of_week,day_of_year,quater
217,2018-09-14,3390,20,1,2018,9,September,37,14,Friday,4,257,3
437,2019-08-04,2830,14,21,2019,8,August,31,4,Sunday,6,216,3
965,2019-05-13,1980,6,1,2019,5,May,20,13,Monday,0,133,2
854,2019-07-12,4030,0,2,2019,7,July,28,12,Friday,4,193,3
115,2018-10-13,5779,13,6,2018,10,October,41,13,Saturday,5,286,4

In [151]:
# Day is weekend or not
order["is_weekend"] = np.where(order["day_name"].isin(["Saturday", "Sunday"]), 1, 0)
order.sample(5)

,date,product_id,city_id,orders,year,month,month_name,week_of_year,day,day_name,day_of_week,day_of_year,quater,is_weekend
939,2018-08-07,5278,13,1,2018,8,August,32,7,Tuesday,1,219,3,0
766,2018-07-13,3454,14,8,2018,7,July,28,13,Friday,4,194,3,0
670,2018-10-24,3051,7,2,2018,10,October,43,24,Wednesday,2,297,4,0
475,2019-07-25,2898,18,98,2019,7,July,30,25,Thursday,3,206,3,0
586,2019-06-26,2563,18,8,2019,6,June,26,26,Wednesday,2,177,2,0

In [152]:
# What is the semester
order["semester"] = np.where(order["quater"].isin([1, 2]), 1, 2)
order.sample(5)

,date,product_id,city_id,orders,year,month,month_name,week_of_year,day,day_name,day_of_week,day_of_year,quater,is_weekend,semester
873,2019-07-20,6933,25,8,2019,7,July,29,20,Saturday,5,201,3,1,2
900,2018-10-09,6803,19,23,2018,10,October,41,9,Tuesday,1,282,4,0,2
773,2019-11-23,1479,16,3,2019,11,November,47,23,Saturday,5,327,4,1,2
78,2019-05-28,3044,7,7,2019,5,May,22,28,Tuesday,1,148,2,0,1
866,2019-11-27,1307,1,7,2019,11,November,48,27,Wednesday,2,331,4,0,2

In [153]:
import datetime
today = datetime.datetime.today()

today

datetime.datetime(2026, 7, 21, 18, 12, 49, 675864)

In [154]:
days = (today - order["date"]).dt.days
days

0      2415
1      2897
2      2828
3      2530
4      2753
       ...
995    2843
996    2784
997    2632
998    2697
999    2471
Name: date, Length: 1000, dtype: int64

In [155]:
# If you only need the whole number of months (floor)
months = (today.year - order["date"].dt.year) * 12 + (today.month - order["date"].dt.month)
months

0      79
1      95
2      93
3      83
4      90
       ..
995    93
996    91
997    86
998    88
999    81
Name: date, Length: 1000, dtype: int32

# HANDLING TIME

In [156]:
msg["hour"] = msg["date"].dt.hour
msg["minute"] = msg["date"].dt.minute
msg["second"] = msg["date"].dt.second
msg["only_time"] = msg["date"].dt.time
msg["only_date"] = msg["date"].dt.date
msg.sample(5)

,date,msg,hour,minute,second,only_time,only_date
467,2014-07-07 01:21:00,Дима 30/182/82 ухожен интересен с чувством юмо...,1,21,0,01:21:00,2014-07-07
621,2016-01-17 00:19:00,Катя я тебе люблю. Ваня,0,19,0,00:19:00,2016-01-17
215,2016-04-10 23:39:00,Познакомлюсь с парнем 20 лет мне 18. буду нежн...,23,39,0,23:39:00,2016-04-10
327,2014-12-22 01:24:00,п34 192 85 позн с одной единственой для сер от...,1,24,0,01:24:00,2014-12-22
351,2013-12-07 23:06:00,М38.175.75Ищу дев.для неч.вст.отвечу на фото и...,23,6,0,23:06:00,2013-12-07

In [157]:
today - msg["date"]

0     4601 days 17:22:49.675864
1     4465 days 18:32:49.675864
2     4951 days 17:51:49.675864
3     4253 days 17:41:49.675864
4     4650 days 19:01:49.675864
                 ...
995   5240 days 17:22:49.675864
996   4561 days 18:58:49.675864
997   5026 days 18:35:49.675864
998   5142 days 18:38:49.675864
999   4414 days 18:47:49.675864
Name: date, Length: 1000, dtype: timedelta64[us]

In [164]:
seconds = np.round((today - msg["date"]) / np.timedelta64(1, 's'), 0)
hours = np.round((today - msg["date"]) / np.timedelta64(1, 'h'), 0)
minuts = np.round((today - msg["date"]) / np.timedelta64(1, 'm'), 0)
hours

0      110441.0
1      107179.0
2      118842.0
3      102090.0
4      111619.0
         ...
995    125777.0
996    109483.0
997    120643.0
998    123427.0
999    105955.0
Name: date, Length: 1000, dtype: float64