In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn as skl

In [2]:
titanic = pd.read_csv("./titanic_toy.csv")
titanic.sample(10)

      Age     Fare  Family  Survived
542  11.0  31.2750       6         0
41   27.0  21.0000       1         0
822  38.0   0.0000       0         0
759  33.0  86.5000       0         1
857  51.0  26.5500       0         1
250   NaN   7.2500       0         0
852   9.0  15.2458       2         0
860  41.0      NaN       2         0
437  24.0  18.7500       5         1
410   NaN   7.8958       0         0

In [3]:
x = titanic.iloc[::, :3:]
y = titanic.iloc[::, -1]

In [ ]:
x_train, x_test, y_train, y_test = skl.model_selection.train_test_split(x, y, test_size= 0.2, random_state= 42)

mi = skl.impute.MissingIndicator()   # same as skl.imputer.SimpleImputer(add_indicator= True)
x_train_mi = mi.fit_transform(x_train)
x_test_mi = mi.transform(x_test)

In [7]:
mi.features_

array([0, 1])

In [15]:
x_train_mi

array([[False, False],
       [False, False],
       [False, False],
       ...,
       [False,  True],
       [False, False],
       [False, False]], shape=(712, 2))

In [16]:
x_train["Age_imputed"] = x_train_mi[:, 0]
x_train["Fare_imputed"] = x_train_mi[:, 1]

In [17]:
x_train

      Age      Fare  Family  Age_imputed  Fare_imputed
331  45.5   28.5000       0        False         False
733  23.0   13.0000       0        False         False
382  32.0    7.9250       0        False         False
704  26.0    7.8542       1        False         False
813   6.0   31.2750       6        False         False
..    ...       ...     ...          ...           ...
106  21.0    7.6500       0        False         False
270   NaN   31.0000       0         True         False
860  41.0       NaN       2        False          True
435  14.0  120.0000       3        False         False
102  21.0   77.2875       1        False         False

[712 rows x 5 columns]