In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn as skl

In [7]:
customer = pd.read_csv("./customer.csv")
customer.sample(10)

    age  gender   review education purchased
27   69  Female     Poor        PG        No
38   45  Female     Good    School        No
20   57  Female  Average    School       Yes
8    65  Female  Average        UG        No
25   57  Female     Good    School        No
45   61    Male     Poor        PG       Yes
1    68  Female     Poor        UG        No
35   74    Male     Poor    School       Yes
14   15    Male     Poor        PG       Yes
39   76    Male     Poor        PG        No

In [8]:
customer = customer.iloc[::, 2::]
customer.sample(10)

     review education purchased
37  Average        PG       Yes
8   Average        UG        No
14     Poor        PG       Yes
47     Good        PG       Yes
48     Good        UG       Yes
35     Poor    School       Yes
24  Average        PG       Yes
49     Good        UG        No
46     Poor        PG        No
38     Good    School        No

In [26]:
x_train, x_test, y_train, y_test = skl.model_selection.train_test_split(customer.iloc[::, :2:], customer.iloc[::, -1], test_size= 0.2)


ordinalEncoder = skl.preprocessing.OrdinalEncoder(categories=[["Poor", "Average", "Good"], ["PG", "School", "UG"]])

ordinalEncoder.fit(x_train)
x_train_oe = ordinalEncoder.transform(x_train)
x_test_oe = ordinalEncoder.transform(x_test)

x_train_oe = pd.DataFrame(x_train_oe, columns= x_train.columns, dtype= int)
x_test_oe = pd.DataFrame(x_test_oe, columns= x_test.columns, dtype= int)

In [27]:
x_test_oe.sample(10)

   review  education
8       1          2
3       1          1
6       0          0
7       2          2
9       0          1
1       1          2
4       0          2
5       2          0
2       1          1
0       0          0

In [17]:
ordinalEncoder.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['PG', 'School', 'UG'], dtype=object)]

In [22]:
labelEncoding = skl.preprocessing.LabelEncoder()

labelEncoding.fit(y_train)
y_train_le = labelEncoding.transform(y_train)
y_test_le = labelEncoding.transform(y_test)

y_train_le = pd.DataFrame(y_train_le)
y_test_le = pd.DataFrame(y_test_le)

In [28]:
y_test_le

   0
0  0
1  0
2  1
3  0
4  0
5  1
6  0
7  1
8  1
9  1

In [29]:
labelEncoding.classes_

array(['No', 'Yes'], dtype=object)